import { type Event } from "@/types/event";

export const mockEvents: Event[] = [
  {
    _id: "1",
    title: "Margalla Trail...",
    description: "A high-energy morning trail run through the scenic Margalla hills.",
    organizerId: "org1",
    organizerProfileId: { _id: "org1", brandName: "UAP IT Society", logoUrl: "" } as any,
    categoryId: "c1",
    category: "Education",
    type: "physical",
    venueName: "Serena Hotel",
    address: "Islamabad",
    city: "Islamabad",
    dateTime: "2024-04-23T10:00:00.000Z",
    timezone: "Asia/Karachi",
    isPaid: true,
    ticketPrice: 1500,
    status: "posted",
    bannerUrl: "",
    cardImageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    interestedCount: 120,
    viewsCount: 500,
    isAiGenerated: false,
    registrationMethod: "native",
    tags: ["run", "trail", "morning"],
    coordinates: { type: "Point", coordinates: [73.0479, 33.6844] },
    customFormSchema: [],
    speakers: [],
    agenda: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "2",
    title: "Wealth Expo 2026",
    description: "Master your financial future with leading experts in the industry.",
    organizerId: "org2",
    organizerProfileId: { _id: "org2", brandName: "Finance Pakistan", logoUrl: "" } as any,
    categoryId: "c2",
    category: "Technology",
    type: "virtual",
    venueName: "Online Webinar",
    address: "",
    city: "Online Webinar",
    dateTime: "2026-04-24T14:00:00.000Z",
    timezone: "Asia/Karachi",
    isPaid: false,
    ticketPrice: 0,
    status: "posted",
    bannerUrl: "",
    cardImageUrl: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&q=80",
    interestedCount: 450,
    viewsCount: 1200,
    isAiGenerated: false,
    registrationMethod: "native",
    tags: ["finance", "expo", "virtual"],
    coordinates: { type: "Point", coordinates: [0, 0] },
    customFormSchema: [],
    speakers: [],
    agenda: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "3",
    title: "Peshawar Music Festival",
    description: "An evening of fusion melodies featuring local artists.",
    organizerId: "org3",
    organizerProfileId: { _id: "org3", brandName: "Eventify Live", logoUrl: "" } as any,
    categoryId: "c3",
    category: "Entertainment",
    type: "physical",
    venueName: "Hayatabad Park",
    address: "Peshawar",
    city: "Peshawar",
    dateTime: "2024-04-25T20:00:00.000Z",
    timezone: "Asia/Karachi",
    isPaid: true,
    ticketPrice: 500,
    status: "posted",
    bannerUrl: "",
    cardImageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80",
    interestedCount: 300,
    viewsCount: 800,
    isAiGenerated: false,
    registrationMethod: "native",
    tags: ["music", "festival", "entertainment"],
    coordinates: { type: "Point", coordinates: [71.5249, 34.0151] },
    customFormSchema: [],
    speakers: [],
    agenda: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "4",
    title: "Karakoram Cycling",
    description: "A breathtaking journey through the peaks and valleys.",
    organizerId: "org4",
    organizerProfileId: { _id: "org4", brandName: "Adventure PK", logoUrl: "" } as any,
    categoryId: "c4",
    category: "Sports",
    type: "physical",
    venueName: "Gilgit",
    address: "Pakistan",
    city: "Gilgit, Pakistan",
    dateTime: "2024-04-26T06:00:00.000Z",
    timezone: "Asia/Karachi",
    isPaid: true,
    ticketPrice: 2000,
    status: "posted",
    bannerUrl: "",
    cardImageUrl: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&q=80",
    interestedCount: 85,
    viewsCount: 400,
    isAiGenerated: false,
    registrationMethod: "native",
    tags: ["cycling", "sports", "adventure"],
    coordinates: { type: "Point", coordinates: [74.3587, 35.9208] },
    customFormSchema: [],
    speakers: [],
    agenda: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockOrganizers = [
  {
    _id: "org1",
    brandName: "UAP IT Society",
    logoUrl: "",
    city: "Islamabad",
    followersCount: 1200,
    bio: "Hosting the best tech events in Islamabad."
  },
  {
    _id: "org2",
    brandName: "Finance Pakistan",
    logoUrl: "",
    city: "Online",
    followersCount: 850,
    bio: "Empowering you with financial knowledge."
  },
];

export const mockUserProfile = {
  _id: "user1",
  name: "Inayat ur Rehman",
  email: "inayat@example.com",
  location: "Peshawar",
  stats: {
    attended: 0,
    followers: 0,
    following: 10,
  }
};
